name: nima
description: Nima runtime for flutter.
version: 1.0.5
author: "2Dimensions Team <info@2dimensions.com>"
homepage: https://github.com/2d-inc/Nima-Flutter
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter